'\" t
.\"     Title: gs
.\"    Author: Ivan Jacob Agaloos Pesigan
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2020-03-29
.\"    Manual: gs Manual
.\"    Source: gs 1.0.0
.\"  Language: English
.\"
.TH "GS" "1" "2020-03-29" "gs 1.0.0" "gs Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
gs \- checks status of all git repositories in a given directory
.SH "SYNOPSIS"
.sp
\fBgs\fP [\fIOPTION\fP]
.SH "DESCRIPTION"
.sp
The \fBgs(1)\fP command
recursively checks status of all git repositories in a given directory.
Checks the $HOME directory by default.
.SH "OPTIONS"
.sp
\fB\-d\fP
.RS 4
By default,
checks the $HOME directory by default.
An optional directory can be provided
using the \-d option.
.RE
.SH "EXAMPLES"
.SS "Default"
.sp
Checks $HOME directory.
.sp
.if n .RS 4
.nf
gs
.fi
.if n .RE
.SS "Optional Directory"
.sp
.if n .RS 4
.nf
gs "$HOME/scripts"
.fi
.if n .RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Sucess.
.RE
.sp
\fB1\fP
.RS 4
Failure.
.RE
.SH "AUTHOR"
.sp
Ivan Jacob Agaloos Pesigan <\c
.MTO "i.j.a.pesigan\(atconnect.um.edu.mo" "" ">"
.SH "LICENSE AND COPYRIGHT"
.sp
Copyright (C) 2020 Ivan Jacob Agaloos Pesigan.
Free use of this software is granted
under the terms of the MIT License.
.SH "AUTHOR"
.sp
Ivan Jacob Agaloos Pesigan